# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18ZMic5lfbhaxi-g1Fe02rPOcjJjjTIJq
"""
import streamlit as st
from datetime import date
from travel_agent import app

st.set_page_config(page_title="AI Travel Concierge", page_icon="🌍")

st.title("🌍 Dynamic Travel Concierge")
st.write("Plan your trip with weather-aware AI")

# --- User Inputs ---
source = st.text_input("Source City", "Hyderabad")
destination = st.text_input("Destination", "London")
start_date = st.date_input("Start Date", date.today())
days = st.slider("Number of Days", 1, 14, 5)

# --- Generate Button ---
if st.button("Generate Itinerary"):
    if not source or not destination:
        st.warning("Please enter both source and destination.")
    else:
        with st.spinner("Planning your trip..."):

            try:
                result = app.invoke({
                    "source": source,
                    "destination": destination,
                    "start_date": start_date,
                    "days": days
                })

                st.success("Trip Planned!")

                # 🗺️ Itinerary
                st.subheader("🗺️ Itinerary")

                # Render formatted itinerary
                for line in result["itinerary"]:
                    if line.lower().startswith("day"):
                        st.markdown(f"### {line}")
                    elif line.strip().startswith("-"):
                        st.markdown(line)
                    else:
                        st.write(line)

                # ✈️ Flights
                st.subheader("✈️ Recommended Flights")
                st.info(result.get("flights", "No flight data"))

                # 🏨 Hotels
                st.subheader("🏨 Recommended Hotels")
                st.success(result.get("hotels", "No hotel data"))

            except Exception as e:
                st.error(f"Error planning trip: {e}")