# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18ZMic5lfbhaxi-g1Fe02rPOcjJjjTIJq
"""
import streamlit as st
from datetime import date
from travel_agent import app

st.set_page_config(page_title="AI Travel Concierge", page_icon="🌍", layout="wide")

# ---------- Helper: Weather Icons ----------
def get_weather_icon(text):
    text = text.lower()
    if "rain" in text:
        return "🌧️"
    if "cloud" in text:
        return "☁️"
    if "clear" in text or "sun" in text:
        return "☀️"
    if "snow" in text:
        return "❄️"
    if "storm" in text:
        return "⛈️"
    return "🌤️"


# ---------- Title ----------
st.title("🌍 Dynamic Travel Concierge")
st.caption("AI-powered travel planning with weather intelligence")

st.divider()

# ---------- Inputs ----------
col1, col2 = st.columns(2)

with col1:
    source = st.text_input("Source City", "Hyderabad")

with col2:
    destination = st.text_input("Destination", "London")

col3, col4 = st.columns(2)

with col3:
    start_date = st.date_input("Start Date", date.today())

with col4:
    days = st.slider("Trip Duration (days)", 1, 14, 5)

st.divider()

# ---------- Route Display ----------
if source and destination:
    st.markdown(
    f"""
    <div style="text-align:center; font-size:22px; font-weight:600;">
        {source.title()} ✈️ {destination.title()}
    </div>
    """,
    unsafe_allow_html=True
)

st.divider()

# ---------- Generate Button ----------
if st.button("✨ Generate Itinerary"):
    with st.spinner("Planning your perfect trip..."):

        try:
            result = app.invoke({
                "source": source,
                "destination": destination,
                "start_date": start_date,
                "days": days
            })

            st.success("Trip Planned Successfully!")

            # ---------- Itinerary ----------
            st.subheader("🗺️ Your Itinerary")

            for item in result["itinerary"]:
                icon = get_weather_icon(item)
                st.markdown(
        f"""
        <div style="
            padding:12px;
            border-radius:8px;
            margin-bottom:8px;
            background-color:#f5f7fb;">
            {icon} {item}
        </div>
        """,
        unsafe_allow_html=True
    )

            st.divider()

            # ---------- Flights & Hotels ----------
            colA, colB = st.columns(2)

            with colA:
                st.subheader("✈️ Recommended Flights")
                st.info(result.get("flights", "No flight data available"))

            with colB:
                st.subheader("🏨 Recommended Hotels")
                st.success(result.get("hotels", "No hotel data available"))

        except Exception as e:
            st.error(f"Error planning trip: {e}")
