# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18ZMic5lfbhaxi-g1Fe02rPOcjJjjTIJq
"""
import streamlit as st
from datetime import date
from travel_agent import app
from geopy.geocoders import Nominatim

# ---------- Page Config ----------
st.set_page_config(
    page_title="AI Travel Concierge",
    page_icon="🌍",
    layout="wide"
)

# ---------- Helper: Weather Icons ----------
def get_weather_icon(text):
    text = text.lower()
    if "rain" in text:
        return "🌧️"
    if "cloud" in text:
        return "☁️"
    if "clear" in text or "sun" in text:
        return "☀️"
    if "snow" in text:
        return "❄️"
    if "storm" in text:
        return "⛈️"
    return "🌤️"

# ---------- Helper: Clean itinerary text ----------
def clean_itinerary_line(line: str):
    """
    Removes weather text like 'Clear:' or 'Clouds:' from itinerary lines.
    Example:
    'Day 1: Clear: - Explore Goa' → 'Day 1: - Explore Goa'
    """
    parts = line.split(":", 2)

    if len(parts) == 3:
        day_part = parts[0]
        activities = parts[2].strip()
        return f"{day_part}: {activities}"

    return line

# ---------- Helper: Get Coordinates ----------
def get_coordinates(city):
    geolocator = Nominatim(user_agent="travel_app")
    location = geolocator.geocode(city)
    if location:
        return location.latitude, location.longitude
    return None, None

# ---------- Title ----------
st.title("🌍 Dynamic Travel Concierge")
st.caption("AI-powered travel planning with weather intelligence")

st.divider()

# ---------- Inputs ----------
col1, col2 = st.columns(2)

with col1:
    source = st.text_input("Source City", "Hyderabad")

with col2:
    destination = st.text_input("Destination", "Goa")

col3, col4 = st.columns(2)

with col3:
    start_date = st.date_input("Start Date", date.today())

with col4:
    days = st.slider("Trip Duration (days)", 1, 14, 5)

st.divider()

# ---------- Route Display ----------
if source and destination:
    st.markdown(
        f"<h3 style='text-align:center'>{source.title()} ➜ ✈️ ➜ {destination.title()}</h3>",
        unsafe_allow_html=True
    )

    # ---------- Map View ----------
    lat, lon = get_coordinates(destination)
    if lat and lon:
        st.map({"lat": [lat], "lon": [lon]})

st.divider()

# ---------- Generate Button ----------
if st.button("✨ Generate Itinerary"):
    if not source or not destination:
        st.warning("Please enter both source and destination.")
    else:
        with st.spinner("Planning your perfect trip..."):

            try:
                result = app.invoke({
                    "source": source,
                    "destination": destination,
                    "start_date": start_date,
                    "days": days
                })

                st.success("Trip Planned Successfully!")

                # ---------- Itinerary ----------
                st.subheader("🗺️ Your Itinerary")

                for item in result["itinerary"]:
                    icon = get_weather_icon(item)
                    clean_line = clean_itinerary_line(item)
                    st.markdown(f"### {icon} {clean_line}")

                st.divider()

                # ---------- Flights & Hotels ----------
                colA, colB = st.columns(2)

                with colA:
                    st.subheader("✈️ Recommended Flights")
                    st.info(result.get("flights", "No flight data available"))

                with colB:
                    st.subheader("🏨 Recommended Hotels")
                    st.success(result.get("hotels", "No hotel data available"))

            except Exception as e:
                st.error(f"Error planning trip: {e}")
